spring.application.name=employee management system
#management.datadog.metrics.export.apiKey=temp
server.port=6066

spring.cloud.zookeeper.connect-string=localhost:2181


## H2 database configuration
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
## JPA settings
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
## Enable H2 console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# ===============================
# = DATA SOURCE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/ems
spring.datasource.username=root
spring.datasource.password=Ankit@2625
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# = JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect